### ISSUE TITLE
Unity license error during test

### ISSUE THREAD

**Issue by 2CAN0** [CarlHalstead/Jenkins-for-Unity-with-DigitalOcean#1]
When ever I start a build I get the error that my license is not active. I have already tried reinstalling Unity. (I have started unity with my vnc and it worked fine)
Error:
+ /opt/unity/2019.3.0f1/Editor/Unity -projectPath /var/lib/jenkins/workspace/JenkinsTest/ -executeMethod UnityBuild.BuildPlatforms -buildPath /var/lib/jenkins/workspace/JenkinsTest/_Final_/ -windows64 -batchmode -nographics -quit
[LicensingClient] ERROR Failed to connect to local IPC
[Licensing::Module] Failed to connect to channel: LicenseClient-jenkins
[Licensing::Module] Successfully launched the LicensingClient
[Licensing::Module] Successfully connected to LicensingClient on channel: LicenseClient-jenkins
[SignatureVerifier] Application signature verification not supported on this platform.
[Licensing::Module] Successfully launched and connected to LicensingClient
Entitlement-based licensing initiated
[LicensingClient] Licenses Updated successfully in LicensingClient
DisplayProgressbar: Unity license
[UnityConnectServicesConfig] config is NOT valid, switching to default
[Licensing::Module] License is not active (com.unity.editor.headless). HasEntitlements will fail.

**Comment by CarlHalstead** [comment]
Thanks for opening this issue!
Lets see if we can fix this!

My first question would be, are you signed into the Unity Hub? I assume yes, correct?

I have found this thread and issue which seems to be related:

https://forum.unity.com/threads/batch-mode-license-activation-fails-in-a-docker-container.748325/
https://issuetracker.unity3d.com/issues/cannot-activate-license-within-a-docker-container

> Running Unity in a Docker container is a common pattern for building CI, so this is going to present a major blocker to updating for many people. In our case, releases up to 2019.1 are working well, but with 2019.3 betas we've started to run into trouble.

The issue has been marked as 'Won't Fix' with it apparently being fixed in 2020.1.

My first suggestion would be to look at the firewall using `ufw status` and telling me what rules are allowed through the firewall. It may just be that HTTP/HTTPS need to be allowed through.

My second suggestion would be to (on your own machine) disable the internet and attempt to sign in to Unity or the Unity Hub. You should then be presented with the following screen.

![](https://docs.unity3d.com/uploads/Main/communicationProblem.png)

If you proceed with the manual activation you should get a license key file at the end. (.ulf file I believe). Transfer this file to your Droplet however you wish. Place it somewhere all users on your Droplet can access, the root of /opt/unity perhaps.

You could then append an argument to Unity launch command like so:

`"$UNITY_PATH/$UNITY_VERSION/Editor/Unity" -projectPath "$WORKSPACE/" -executeMethod UnityBuild.BuildPlatforms -buildPath "$WORKSPACE/_Final_/" -windows64 -manualLicenseFile "Your/License/FilePath.ulf" -batchmode -nographics -quit`

My third and final suggestion which I certainly do not recommend but for testing and debugging purposes you could try would be to add the `-username "YourUnityUsernameHere"` and `-password "YourUnityPasswordHere"` to the launch arguments. This assumes that your Jenkins configurations are not public. **Make sure to blank these out if you share a copy of the log!**

Apologies that it couldn't be simpler! Hope you can get it working!

**Comment by 2CAN0** [comment]
option2 might indeed work I will try that and I will try an older Unity version
I have ufw inactive (I know it's safe when it's on)

**Comment by 2CAN0** [comment]
I have this license error with manual license activation.
The new command I used was `"$UNITY_PATH/$UNITY_VERSION/Editor/Unity" -projectPath "$WORKSPACE/" -executeMethod UnityBuild.BuildPlatforms -buildPath "$WORKSPACE/_Final_/" -windows64 -manualLicenseFile "/opt/unity/Unity_lic.ulf" -batchmode -nographics -quit`

But there is another error I get 
`Build step 'Execute shell' marked the build as Failure` :disappointed:

**Comment by CarlHalstead** [comment]
> But there is another error I get
Build step 'Execute shell' marked the build as Failure 😞

We will need to examine the actual error if we are to continue. What you have quoted is just Jenkins knowing that something has failed and cancelling the build. If it is feasible, could you post the entire log?

If you have a different error though that is probably a good thing and means we may be one step closer!

**Comment by 2CAN0** [comment]
This is the log
[log.txt](https://github.com/CarlHalstead/Jenkins-for-Unity-with-DigitalOcean/files/3950425/log.txt)

This is where I removed the executeMethod command to test if it was going wrong at executing the method

**Comment by CarlHalstead** [comment]
Interesting. Have you tried starting a build with the new license parameter and the executeMethod parameter yet to start a normal build? That is the log I would like to see if possible. It should give us more information.

**Comment by 2CAN0** [comment]
Only the new license parameter and the execute one?

**Comment by CarlHalstead** [comment]
The one you posted previously:

> "$UNITY_PATH/$UNITY_VERSION/Editor/Unity" -projectPath "$WORKSPACE/" -executeMethod UnityBuild.BuildPlatforms -buildPath "$WORKSPACE/_Final_/" -windows64 -manualLicenseFile "/opt/unity/Unity_lic.ulf" -batchmode -nographics -quit

So the one included in this guide with the added -manualLicenseFile argument.

**Comment by 2CAN0** [comment]
This is the log with this command: 
"$UNITY_PATH/$UNITY_VERSION/Editor/Unity" -projectPath "$WORKSPACE/" -executeMethod UnityBuild.BuildPlatforms -buildPath "$WORKSPACE/Final/" -windows64 -manualLicenseFile "/opt/unity/Unity_lic.ulf" -batchmode -nographics -quit

[log.txt](https://github.com/CarlHalstead/Jenkins-for-Unity-with-DigitalOcean/files/3950496/log.txt)

Too me it looks like it's failing to open the project

**Comment by CarlHalstead** [comment]
Hmm pretty strange. I wonder if this is because of the comment on that issue tracker I linked previously mentioning that for whatever reason 2019.3 did not work. 

Would it be possible to test another Unity version? I had luck with 2019.2.3 previously but anything that is not 2019.3 is worth a shot.

Thanks for the information thus far.

EDIT: I am perplexed by this because the log appears to just end. Unity appears to close without any error.

**Comment by 2CAN0** [comment]
I will try 2019.2.15

**Comment by 2CAN0** [comment]
I get the exact same error with 2019.2.15. Do you know where I can find old unity versions for linux?

**Comment by CarlHalstead** [comment]
There are some here:

https://forum.unity.com/threads/unity-on-linux-release-notes-and-known-issues.350256

Note that these are not through the Unity Hub. I believe these installers install straight into the directory you point to without creating a sub-directory so be aware of that, you will want to create a new folder first and install there.

**Comment by 2CAN0** [comment]
Get the same error with unity 2019.1.0f2

**Comment by CarlHalstead** [comment]
Ugh. How peculiar.

Could you post the log from the 2019.1.0f2 attempt? I know it is the same but I just want to make sure.

Is the project you are trying to build public? If so, could I have a link so that I can try it myself. If not, I will just create my own temporary project to test.

**Comment by 2CAN0** [comment]
This is the test project I'm using:
https://github.com/2CAN0/JenkinsTest

This is the 2019.1.0f2 log (I enabled time stamps in this log):
[log.txt](https://github.com/CarlHalstead/Jenkins-for-Unity-with-DigitalOcean/files/3950747/log.txt)

**Comment by 2CAN0** [comment]
It might have to do with the editor.log which it can't find

**Comment by CarlHalstead** [comment]
One thing I have noticed immediately is that your Editor folder is in the wrong place. It should be inside of your Assets folder. After that has been corrected, try to build and let me know how it goes.

I should make it clearer that this Editor folder should be within the Assets folder, my mistake!

**Comment by 2CAN0** [comment]
It works now, the problems I had were:
- Having the editor folder in the wrong directory
- The artifacts options gave an error which failed the builds
- The manual license file verification makes the build fail

I will try the manual license again in combo with unity 2019.3

**Update:**
- Unity 2019.3.0f1 - Doesn't work
- Unity 2019.2.15f1 - Does work

**Comment by CarlHalstead** [comment]
That's great to hear!

Just let me know when everything is working as expected and the thread can then be closed.
